name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    name: Test with on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: |
        yarn install --frozen-lockfile                                                                                                                                                                                        
        yarn build
        yarn test

  trigger_publish:
    name: Trigger publish.yaml workflow if package.json version updated ( and secrets.PAT is set ).
    runs-on: ubuntu-latest
    env:
      PAT: ${{secrets.PAT}}
    if: github.event_name == 'push' && github.event.head_commit.author.name != 'ts_ci'
    needs: test
    steps:

    - name: Get version on latest
      id: v_latest
      uses: garronej/github_actions_toolkit@v1.11
      with: 
        action_name: get_package_json_version
        owner: ${{github.repository_owner}}
        repo: ${{github.event.repository.name}}
        branch: latest
        compare_to_version: '0.0.0'

    - name: Get version on main
      id: v_main
      uses: garronej/github_actions_toolkit@v1.11
      with: 
        action_name: get_package_json_version
        owner: ${{github.repository_owner}}
        repo: ${{github.event.repository.name}}
        branch: ${{ github.sha }}
        compare_to_version: ${{steps.v_latest.outputs.version || '0.0.0'}}

    - name: 'Trigger the ''publish'' workflow' 
      if: ${{ !!env.PAT && steps.v_main.outputs.compare_result == '1' }}
      uses: garronej/github_actions_toolkit@v1.11
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        action_name: dispatch_event
        owner: ${{github.repository_owner}}
        repo: ${{github.event.repository.name}}
        event_type: publish
        client_payload_json: |
          ${{
            format(
              '{{"from_version":"{0}","to_version":"{1}","repo":"{2}"}}',
              steps.v_latest.outputs.version,
              steps.v_main.outputs.version,
              github.event.repository.name
            )
          }}
