on:
  repository_dispatch:
    types: publish

jobs:

  docker:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.8.4
        with:
          images: ${{github.repository_owner}}/${{github.event.client_payload.repo}} # list of Docker images to use as base name for tags
          github-token: ${{ secrets.PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{github.repository_owner}}/${{github.event.client_payload.repo}}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build_keycloak_theme:
    runs-on: ubuntu-latest
    name: Build keycloak theme
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-node@v1
    - run: |
        yarn install --frozen-lockfile                                                                                                                                                                                        
        yarn build
        npx build-keycloak-theme
    - name: Upload keycloak theme
      uses: actions/upload-artifact@v2
      with:
        name: keycloak_theme
        path: build_keycloak/target/*keycloak-theme*.jar

  update_changelog:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest
    needs:
      - build_keycloak_theme
      - docker
    steps:
    - if: ${{ !!github.event.client_payload.from_version }}
      uses: garronej/github_actions_toolkit@v1.11
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        action_name: update_changelog
        owner: ${{github.repository_owner}}
        repo: ${{github.event.client_payload.repo}}
        branch_behind: latest
        branch_ahead: main
        commit_author_email: ts_ci@github.com
        exclude_commit_from_author_names_json: '["ts_ci"]'

  publish:
    runs-on: ubuntu-latest
    needs: update_changelog
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
    - name: Remove .github directory, useless on 'latest' branch
      run: rm -r .github
    - name: Remove branch 'latest' 
      continue-on-error: true
      run: |
        git branch -d latest || true
        git push origin :latest
    - name: Create the new 'latest' branch
      run: |
        git branch latest
        git checkout latest
        git push origin latest
    - name: Download keycloak_theme
      id: id_dl
      uses: actions/download-artifact@v2
      with:
        name: keycloak_theme
    - run: mv *keycloak-theme*.jar keycloak-theme.jar
    - name: Release body
      id: id_rb
      run: |
        if [ "$FROM_VERSION" = "" ]; then
            echo "::set-output name=body::🚀"
        else
            echo "::set-output name=body::📋 [CHANGELOG](https://github.com/$OWNER/$REPO/blob/$REF/CHANGELOG.md)"
        fi
      env: 
        FROM_VERSION: ${{ github.event.client_payload.from_version }}
        OWNER: ${{github.repository_owner}}
        REPO: ${{github.event.client_payload.repo}}
        REF: v${{github.event.client_payload.to_version}}
    - name: Create Release
      uses: ThomasPiskol/action-gh-release@8eb01d050288728124e879e2e724873f39433141
      with:
        name: Release v${{ github.event.client_payload.to_version }}
        tag_name: v${{ github.event.client_payload.to_version }}
        target_commitish: latest
        files: keycloak-theme.jar
        body: ${{ steps.id_rb.outputs.body }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - name: Push keycloak theme
      run: |
        git config --local user.email "ts_ci@github.com"
        git config --local user.name "ts_ci"
        git add -A
        git commit -am "Upload keycloak theme [automatic]"